example_project/app1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.App1ListView.as_view(), name='app1_list'),
]

example_project/app2/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.App2ListView.as_view(), name='app2_list'),
]

example_project/example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from sitewide.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app1/', include('app1.urls', namespace='app1')),
    url(r'^app2/', include('app2.urls', namespace='app2')),
    url(r'^$', IndexView.as_view(), name='index'),
]

example_project/app1/models.py
from django.db import models

# Create your models here.

example_project/app2/models.py
from django.db import models

# Create your models here.

example_project/app1/views.py
from django.views.generic.base import TemplateView


class App1ListView(TemplateView):
    template_name = 'app1/app1_list.html'

example_project/app2/views.py
from django.views.generic.base import TemplateView


class App2ListView(TemplateView):
    template_name = 'app2/app2_list.html'

example_project/sitewide/views.py
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = 'sitewide/index.html'

example_project/app1/templates/app1/app1_list.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'app1/css/app1.css' %}" />
{% endblock %}

{% block main_content %}

<h1>App1 list</h1>

<div id="demo" class="mb-5"></div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'app1/js/move.js' %}"></script>
{% endblock %}

example_project/app2/templates/app2/app2_list.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block head_extra %}
<link rel="stylesheet" href="{% static 'app2/css/app2.css' %}" />
{% endblock %}

{% block main_content %}

<h1>App2 list</h1>

<div id="demo" class="mb-5"></div>

{% endblock %}

{% block extra_js %}
<script src="{% static 'app2/js/rotate.js' %}"></script>
{% endblock %}

example_project/sitewide/templates/sitewide/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Example project</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'sitewide/css/main.css' %}" />
		{% block head_extra %}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-toggleable-sm navbar-inverse fixed-top bg-inverse">
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="/">Example project!</a>

			<div class="collapse navbar-collapse" id="navbarsExampleDefault">
				<ul class="navbar-nav">
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="main_dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Stuff</a>
						<div class="dropdown-menu" aria-labelledby="main_dropdown">
							<a class="dropdown-item" href="{% url 'app1:app1_list' %}">App1</a>
							<a class="dropdown-item" href="{% url 'app2:app2_list' %}">App2</a>
						</div>
					</li>
				</ul>
			</div>
		</nav>

		<div class="main-content container-fluid">

			{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					{{ message }}
				</div>
			{% endfor %}

			{% block main_content %}
			{% endblock %}

		</div>

		<!-- Run the JS -->
		<script src="{% static 'sitewide/js/lib.js' %}"></script>

		{% block extra_js %}
		{% endblock %}

	</body>
</html>

example_project/sitewide/templates/sitewide/index.html
{% extends 'sitewide/base.html' %}
{% load static %}

{% block main_content %}

<h1>Home</h1>

<ul>
	<li><a href="{% url 'app1:app1_list' %}">App1</a></li>
	<li><a href="{% url 'app2:app2_list' %}">App2</a></li>
</ul>

<img src="{% static 'sitewide/img/sunpig_parent_child.jpg'%}" class="mv-3" />

{% endblock %}